language: php

sudo: false

dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:

    - php: 7.1
      env: PHPUNIT=^7.5
      name: PHP 7.1
    - php: 7.2
      env: PHPUNIT=^8.0
      name: PHP 7.2
    - php: 7.3
      env: PHPUNIT=^8.0
      name: PHP 7.3

before_install:
  - composer self-update --stable --no-interaction
  - composer require friendsofphp/php-cs-fixer phpunit/phpunit:$PHPUNIT --no-update --no-interaction --dev

install:
  - travis_retry composer install --no-suggest --no-interaction

script:
  - vendor/bin/php-cs-fixer fix -v --diff --dry-run
  - vendor/bin/phpunit --verbose --configuration phpunit.xml.dist  --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
