<?php return [
  1 => [
        'start_date' => '2011-01-04',
        'stop_date' => '',
        'territory_codes' => 'AI',
        'currency_code' => 'XCD',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Anguilla (British overseas territory) is exempted of VAT.',
    ],
  [
        'start_date' => '1984-01-01',
        'stop_date' => '',
        'territory_codes' => 'AT',
        'currency_code' => 'EUR',
        'rate' => '0.2',
        'rate_type' => 'standard',
        'description' => 'Austria (member state) standard VAT rate.',
    ],
  [
        'start_date' => '1976-01-01',
        'stop_date' => '1984-01-01',
        'territory_codes' => 'AT',
        'currency_code' => 'EUR',
        'rate' => '0.18',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1973-01-01',
        'stop_date' => '1976-01-01',
        'territory_codes' => 'AT',
        'currency_code' => 'EUR',
        'rate' => '0.16',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1984-01-01',
        'stop_date' => '',
        'territory_codes' => 'AT-6691
DE-87491',
        'currency_code' => 'EUR',
        'rate' => '0.19',
        'rate_type' => 'standard',
        'description' => 'Jungholz (Austrian town) special VAT rate.',
    ],
  [
        'start_date' => '1984-01-01',
        'stop_date' => '',
        'territory_codes' => 'AT-6991
AT-6992
AT-6993
DE-87567
DE-87568
DE-87569',
        'currency_code' => 'EUR',
        'rate' => '0.19',
        'rate_type' => 'standard',
        'description' => 'Mittelberg (Austrian town) special VAT rate.',
    ],
  [
        'start_date' => '1996-01-01',
        'stop_date' => '',
        'territory_codes' => 'BE',
        'currency_code' => 'EUR',
        'rate' => '0.21',
        'rate_type' => 'standard',
        'description' => 'Belgium (member state) standard VAT rate.',
    ],
  [
        'start_date' => '1994-01-01',
        'stop_date' => '1996-01-01',
        'territory_codes' => 'BE',
        'currency_code' => 'EUR',
        'rate' => '0.205',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1992-04-01',
        'stop_date' => '1994-01-01',
        'territory_codes' => 'BE',
        'currency_code' => 'EUR',
        'rate' => '0.195',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1983-01-01',
        'stop_date' => '1992-04-01',
        'territory_codes' => 'BE',
        'currency_code' => 'EUR',
        'rate' => '0.19',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1981-07-01',
        'stop_date' => '1983-01-01',
        'territory_codes' => 'BE',
        'currency_code' => 'EUR',
        'rate' => '0.17',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1978-07-01',
        'stop_date' => '1981-07-01',
        'territory_codes' => 'BE',
        'currency_code' => 'EUR',
        'rate' => '0.16',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1971-07-01',
        'stop_date' => '1978-07-01',
        'territory_codes' => 'BE',
        'currency_code' => 'EUR',
        'rate' => '0.18',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1999-01-01',
        'stop_date' => '',
        'territory_codes' => 'BG',
        'currency_code' => 'BGN',
        'rate' => '0.2',
        'rate_type' => 'standard',
        'description' => 'Bulgaria (member state) standard VAT rate.',
    ],
  [
        'start_date' => '1996-07-01',
        'stop_date' => '1999-01-01',
        'territory_codes' => 'BG',
        'currency_code' => 'BGN',
        'rate' => '0.22',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1994-04-01',
        'stop_date' => '1996-07-01',
        'territory_codes' => 'BG',
        'currency_code' => 'BGN',
        'rate' => '0.18',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2011-01-04',
        'stop_date' => '',
        'territory_codes' => 'BM',
        'currency_code' => 'BMD',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Bermuda (British overseas territory) is exempted of VAT.',
    ],
  [
        'start_date' => '2014-01-13',
        'stop_date' => '',
        'territory_codes' => 'CY
GB-BFPO 57
GB-BFPO 58
GB-BFPO 59
UK-BFPO 57
UK-BFPO 58
UK-BFPO 59',
        'currency_code' => 'EUR',
        'rate' => '0.19',
        'rate_type' => 'standard',
        'description' => 'Cyprus (member state) standard VAT rate.
Akrotiri and Dhekelia (British overseas territory) is subjected to Cyprus\' standard VAT rate.',
    ],
  [
        'start_date' => '2013-01-14',
        'stop_date' => '2014-01-13',
        'territory_codes' => 'CY',
        'currency_code' => 'EUR',
        'rate' => '0.18',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2012-03-01',
        'stop_date' => '2013-01-14',
        'territory_codes' => 'CY',
        'currency_code' => 'EUR',
        'rate' => '0.17',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2003-01-01',
        'stop_date' => '2012-03-01',
        'territory_codes' => 'CY',
        'currency_code' => 'EUR',
        'rate' => '0.15',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2002-07-01',
        'stop_date' => '2003-01-01',
        'territory_codes' => 'CY',
        'currency_code' => 'EUR',
        'rate' => '0.13',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2000-07-01',
        'stop_date' => '2002-07-01',
        'territory_codes' => 'CY',
        'currency_code' => 'EUR',
        'rate' => '0.1',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1993-10-01',
        'stop_date' => '2000-07-01',
        'territory_codes' => 'CY',
        'currency_code' => 'EUR',
        'rate' => '0.08',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1992-07-01',
        'stop_date' => '1993-10-01',
        'territory_codes' => 'CY',
        'currency_code' => 'EUR',
        'rate' => '0.05',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2013-01-01',
        'stop_date' => '',
        'territory_codes' => 'CZ',
        'currency_code' => 'CZK',
        'rate' => '0.21',
        'rate_type' => 'standard',
        'description' => 'Czech Republic (member state) standard VAT rate.',
    ],
  [
        'start_date' => '2010-01-01',
        'stop_date' => '2013-01-01',
        'territory_codes' => 'CZ',
        'currency_code' => 'CZK',
        'rate' => '0.2',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2004-05-01',
        'stop_date' => '2010-01-01',
        'territory_codes' => 'CZ',
        'currency_code' => 'CZK',
        'rate' => '0.19',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1995-01-01',
        'stop_date' => '2004-05-01',
        'territory_codes' => 'CZ',
        'currency_code' => 'CZK',
        'rate' => '0.22',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1993-01-01',
        'stop_date' => '1995-01-01',
        'territory_codes' => 'CZ',
        'currency_code' => 'CZK',
        'rate' => '0.23',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2007-01-01',
        'stop_date' => '',
        'territory_codes' => 'DE',
        'currency_code' => 'EUR',
        'rate' => '0.19',
        'rate_type' => 'standard',
        'description' => 'Germany (member state) standard VAT rate.',
    ],
  [
        'start_date' => '1998-04-01',
        'stop_date' => '2007-01-01',
        'territory_codes' => 'DE',
        'currency_code' => 'EUR',
        'rate' => '0.16',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1993-01-01',
        'stop_date' => '1998-04-01',
        'territory_codes' => 'DE',
        'currency_code' => 'EUR',
        'rate' => '0.15',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1983-07-01',
        'stop_date' => '1993-01-01',
        'territory_codes' => 'DE',
        'currency_code' => 'EUR',
        'rate' => '0.14',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1979-07-01',
        'stop_date' => '1983-07-01',
        'territory_codes' => 'DE',
        'currency_code' => 'EUR',
        'rate' => '0.13',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1978-01-01',
        'stop_date' => '1979-07-01',
        'territory_codes' => 'DE',
        'currency_code' => 'EUR',
        'rate' => '0.12',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1968-07-01',
        'stop_date' => '1978-01-01',
        'territory_codes' => 'DE',
        'currency_code' => 'EUR',
        'rate' => '0.11',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1968-01-01',
        'stop_date' => '1968-07-01',
        'territory_codes' => 'DE',
        'currency_code' => 'EUR',
        'rate' => '0.1',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2007-01-01',
        'stop_date' => '',
        'territory_codes' => 'DE-27498',
        'currency_code' => 'EUR',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Heligoland (German island) is exempted of VAT.',
    ],
  [
        'start_date' => '2007-01-01',
        'stop_date' => '',
        'territory_codes' => 'DE-78266
CH-8238',
        'currency_code' => 'EUR',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Busingen am Hochrhein (German territory) is exempted of VAT.',
    ],
  [
        'start_date' => '1992-01-01',
        'stop_date' => '',
        'territory_codes' => 'DK',
        'currency_code' => 'DKK',
        'rate' => '0.25',
        'rate_type' => 'standard',
        'description' => 'Denmark (member state) standard VAT rate.',
    ],
  [
        'start_date' => '1980-06-30',
        'stop_date' => '1992-01-01',
        'territory_codes' => 'DK',
        'currency_code' => 'DKK',
        'rate' => '0.22',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1978-10-30',
        'stop_date' => '1980-06-30',
        'territory_codes' => 'DK',
        'currency_code' => 'DKK',
        'rate' => '0.2025',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1977-10-03',
        'stop_date' => '1978-10-30',
        'territory_codes' => 'DK',
        'currency_code' => 'DKK',
        'rate' => '0.18',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1970-06-29',
        'stop_date' => '1977-10-03',
        'territory_codes' => 'DK',
        'currency_code' => 'DKK',
        'rate' => '0.15',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1968-04-01',
        'stop_date' => '1970-06-29',
        'territory_codes' => 'DK',
        'currency_code' => 'DKK',
        'rate' => '0.125',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1967-07-03',
        'stop_date' => '1968-04-01',
        'territory_codes' => 'DK',
        'currency_code' => 'DKK',
        'rate' => '0.1',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2009-07-01',
        'stop_date' => '',
        'territory_codes' => 'EE',
        'currency_code' => 'EUR',
        'rate' => '0.2',
        'rate_type' => 'standard',
        'description' => 'Estonia (member state) standard VAT rate.',
    ],
  [
        'start_date' => '1993-01-01',
        'stop_date' => '2009-07-01',
        'territory_codes' => 'EE',
        'currency_code' => 'EUR',
        'rate' => '0.18',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1991-01-01',
        'stop_date' => '1993-01-01',
        'territory_codes' => 'EE',
        'currency_code' => 'EUR',
        'rate' => '0.1',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2016-06-01',
        'stop_date' => '',
        'territory_codes' => 'GR
EL',
        'currency_code' => 'EUR',
        'rate' => '0.24',
        'rate_type' => 'standard',
        'description' => 'Greece (member state) standard VAT rate.',
    ],
  [
        'start_date' => '2010-07-01',
        'stop_date' => '2016-06-01',
        'territory_codes' => 'GR
EL',
        'currency_code' => 'EUR',
        'rate' => '0.23',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2010-03-15',
        'stop_date' => '2010-07-01',
        'territory_codes' => 'GR
EL',
        'currency_code' => 'EUR',
        'rate' => '0.21',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2005-04-01',
        'stop_date' => '2010-03-15',
        'territory_codes' => 'GR
EL',
        'currency_code' => 'EUR',
        'rate' => '0.19',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1990-04-28',
        'stop_date' => '2005-04-01',
        'territory_codes' => 'GR
EL',
        'currency_code' => 'EUR',
        'rate' => '0.18',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1988-01-01',
        'stop_date' => '1990-04-28',
        'territory_codes' => 'GR
EL',
        'currency_code' => 'EUR',
        'rate' => '0.16',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1987-01-01',
        'stop_date' => '1988-01-01',
        'territory_codes' => 'GR
EL',
        'currency_code' => 'EUR',
        'rate' => '0.18',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2012-09-01',
        'stop_date' => '',
        'territory_codes' => 'ES',
        'currency_code' => 'EUR',
        'rate' => '0.21',
        'rate_type' => 'standard',
        'description' => 'Spain (member state) standard VAT rate.',
    ],
  [
        'start_date' => '2010-07-01',
        'stop_date' => '2012-09-01',
        'territory_codes' => 'ES',
        'currency_code' => 'EUR',
        'rate' => '0.18',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1995-01-01',
        'stop_date' => '2010-07-01',
        'territory_codes' => 'ES',
        'currency_code' => 'EUR',
        'rate' => '0.16',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1992-08-01',
        'stop_date' => '1995-01-01',
        'territory_codes' => 'ES',
        'currency_code' => 'EUR',
        'rate' => '0.15',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1992-01-01',
        'stop_date' => '1992-08-01',
        'territory_codes' => 'ES',
        'currency_code' => 'EUR',
        'rate' => '0.13',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1986-01-01',
        'stop_date' => '1992-01-01',
        'territory_codes' => 'ES',
        'currency_code' => 'EUR',
        'rate' => '0.12',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2012-09-01',
        'stop_date' => '',
        'territory_codes' => 'ES-CN
ES-GC
ES-TF
IC',
        'currency_code' => 'EUR',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Canary Islands (Spanish autonomous community) is exempted of VAT.',
    ],
  [
        'start_date' => '2012-09-01',
        'stop_date' => '',
        'territory_codes' => 'ES-ML
ES-CE
EA',
        'currency_code' => 'EUR',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Ceuta and Melilla (Spanish autonomous cities) is exempted of VAT.',
    ],
  [
        'start_date' => '2013-01-01',
        'stop_date' => '',
        'territory_codes' => 'FI',
        'currency_code' => 'EUR',
        'rate' => '0.24',
        'rate_type' => 'standard',
        'description' => 'Finland (member state) standard VAT rate.',
    ],
  [
        'start_date' => '2010-07-01',
        'stop_date' => '2013-01-01',
        'territory_codes' => 'FI',
        'currency_code' => 'EUR',
        'rate' => '0.23',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1994-06-01',
        'stop_date' => '2010-07-01',
        'territory_codes' => 'FI',
        'currency_code' => 'EUR',
        'rate' => '0.22',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2013-01-01',
        'stop_date' => '',
        'territory_codes' => 'FI-01
AX',
        'currency_code' => 'EUR',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Aland Islands (Finish autonomous region) is exempted of VAT.',
    ],
  [
        'start_date' => '2011-01-04',
        'stop_date' => '',
        'territory_codes' => 'FK',
        'currency_code' => 'FKP',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Falkland Islands (British overseas territory) is exempted of VAT.',
    ],
  [
        'start_date' => '1992-01-01',
        'stop_date' => '',
        'territory_codes' => 'FO',
        'currency_code' => 'DKK',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Faroe Islands (Danish autonomous country) is exempted of VAT.',
    ],
  [
        'start_date' => '2014-01-01',
        'stop_date' => '',
        'territory_codes' => 'FR
MC',
        'currency_code' => 'EUR',
        'rate' => '0.2',
        'rate_type' => 'standard',
        'description' => 'France (member state) standard VAT rate.
Monaco (sovereign city-state) is member of the EU VAT area and subjected to France\'s standard VAT rate.',
    ],
  [
        'start_date' => '2000-04-01',
        'stop_date' => '2014-01-01',
        'territory_codes' => 'FR
MC',
        'currency_code' => 'EUR',
        'rate' => '0.196',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1995-08-01',
        'stop_date' => '2000-04-01',
        'territory_codes' => 'FR
MC',
        'currency_code' => 'EUR',
        'rate' => '0.206',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1982-07-01',
        'stop_date' => '1995-08-01',
        'territory_codes' => 'FR
MC',
        'currency_code' => 'EUR',
        'rate' => '0.186',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1977-01-01',
        'stop_date' => '1982-07-01',
        'territory_codes' => 'FR
MC',
        'currency_code' => 'EUR',
        'rate' => '0.176',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1973-01-01',
        'stop_date' => '1977-01-01',
        'territory_codes' => 'FR
MC',
        'currency_code' => 'EUR',
        'rate' => '0.2',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1970-01-01',
        'stop_date' => '1973-01-01',
        'territory_codes' => 'FR
MC',
        'currency_code' => 'EUR',
        'rate' => '0.23',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1968-12-01',
        'stop_date' => '1970-01-01',
        'territory_codes' => 'FR
MC',
        'currency_code' => 'EUR',
        'rate' => '0.19',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1968-01-01',
        'stop_date' => '1968-12-01',
        'territory_codes' => 'FR
MC',
        'currency_code' => 'EUR',
        'rate' => '0.1666',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2014-01-01',
        'stop_date' => '',
        'territory_codes' => 'FR-BL
BL',
        'currency_code' => 'EUR',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Saint Barthelemy (French overseas collectivity) is exempted of VAT.',
    ],
  [
        'start_date' => '2014-01-01',
        'stop_date' => '',
        'territory_codes' => 'FR-GF
GF',
        'currency_code' => 'EUR',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Guiana (French overseas department) is exempted of VAT.',
    ],
  [
        'start_date' => '2014-01-01',
        'stop_date' => '',
        'territory_codes' => 'FR-GP
GP',
        'currency_code' => 'EUR',
        'rate' => '0.085',
        'rate_type' => 'standard',
        'description' => 'Guadeloupe (French overseas department) special VAT rate.',
    ],
  [
        'start_date' => '2014-01-01',
        'stop_date' => '',
        'territory_codes' => 'FR-MF
MF',
        'currency_code' => 'EUR',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Saint Martin (French overseas collectivity) is subjected to France\'s standard VAT rate.',
    ],
  [
        'start_date' => '2014-01-01',
        'stop_date' => '',
        'territory_codes' => 'FR-MQ
MQ',
        'currency_code' => 'EUR',
        'rate' => '0.085',
        'rate_type' => 'standard',
        'description' => 'Martinique (French overseas department) special VAT rate.',
    ],
  [
        'start_date' => '2014-01-01',
        'stop_date' => '',
        'territory_codes' => 'FR-NC
NC',
        'currency_code' => 'XPF',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'New Caledonia (French special collectivity) is exempted of VAT.',
    ],
  [
        'start_date' => '2014-01-01',
        'stop_date' => '',
        'territory_codes' => 'FR-PF
PF',
        'currency_code' => 'XPF',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'French Polynesia (French overseas collectivity) is exempted of VAT.',
    ],
  [
        'start_date' => '2014-01-01',
        'stop_date' => '',
        'territory_codes' => 'FR-PM
PM',
        'currency_code' => 'EUR',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Saint Pierre and Miquelon (French overseas collectivity) is exempted of VAT.',
    ],
  [
        'start_date' => '2014-01-01',
        'stop_date' => '',
        'territory_codes' => 'FR-RE
RE',
        'currency_code' => 'EUR',
        'rate' => '0.085',
        'rate_type' => 'standard',
        'description' => 'Reunion (French overseas department) special VAT rate.',
    ],
  [
        'start_date' => '2014-01-01',
        'stop_date' => '',
        'territory_codes' => 'FR-TF
TF',
        'currency_code' => 'EUR',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'French Southern and Antarctic Lands (French overseas territory) is exempted of VAT.',
    ],
  [
        'start_date' => '2014-01-01',
        'stop_date' => '',
        'territory_codes' => 'FR-WF
WF',
        'currency_code' => 'XPF',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Wallis and Futuna (French overseas collectivity) is exempted of VAT.',
    ],
  [
        'start_date' => '2014-01-01',
        'stop_date' => '',
        'territory_codes' => 'FR-YT
YT',
        'currency_code' => 'EUR',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Mayotte (French overseas department) is exempted of VAT.',
    ],
  [
        'start_date' => '2011-01-04',
        'stop_date' => '',
        'territory_codes' => 'GG',
        'currency_code' => 'GBP',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Guernsey (British Crown dependency) is exempted of VAT.',
    ],
  [
        'start_date' => '2011-01-04',
        'stop_date' => '',
        'territory_codes' => 'GI',
        'currency_code' => 'GIP',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Gibraltar (British overseas territory) is exempted of VAT.',
    ],
  [
        'start_date' => '1992-01-01',
        'stop_date' => '',
        'territory_codes' => 'GL',
        'currency_code' => 'DKK',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Greenland (Danish autonomous country) is exempted of VAT.',
    ],
  [
        'start_date' => '2010-07-01',
        'stop_date' => '2016-06-01',
        'territory_codes' => 'GR-34007
EL-34007',
        'currency_code' => 'EUR',
        'rate' => '0.16',
        'rate_type' => 'standard',
        'description' => 'Skyros (Greek island) special VAT rate.',
    ],
  [
        'start_date' => '2010-07-01',
        'stop_date' => '2016-06-01',
        'territory_codes' => 'GR-37002
GR-37003
GR-37005
EL-37002
EL-37003
EL-37005',
        'currency_code' => 'EUR',
        'rate' => '0.16',
        'rate_type' => 'standard',
        'description' => 'Northern Sporades (Greek islands) special VAT rate.',
    ],
  [
        'start_date' => '2010-07-01',
        'stop_date' => '2016-06-01',
        'territory_codes' => 'GR-64004
EL-64004',
        'currency_code' => 'EUR',
        'rate' => '0.16',
        'rate_type' => 'standard',
        'description' => 'Thasos (Greek island) special VAT rate.',
    ],
  [
        'start_date' => '2010-07-01',
        'stop_date' => '2016-06-01',
        'territory_codes' => 'GR-68002
EL-68002',
        'currency_code' => 'EUR',
        'rate' => '0.16',
        'rate_type' => 'standard',
        'description' => 'Samothrace (Greek island) special VAT rate.',
    ],
  [
        'start_date' => '2010-07-01',
        'stop_date' => '',
        'territory_codes' => 'GR-69
EL-69',
        'currency_code' => 'EUR',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Mount Athos (Greek self-governed part) is exempted of VAT.',
    ],
  [
        'start_date' => '2010-07-01',
        'stop_date' => '2016-06-01',
        'territory_codes' => 'GR-81
EL-81',
        'currency_code' => 'EUR',
        'rate' => '0.16',
        'rate_type' => 'standard',
        'description' => 'Dodecanese (Greek department) special VAT rate.',
    ],
  [
        'start_date' => '2010-07-01',
        'stop_date' => '2016-06-01',
        'territory_codes' => 'GR-82
EL-82',
        'currency_code' => 'EUR',
        'rate' => '0.16',
        'rate_type' => 'standard',
        'description' => 'Cyclades (Greek department) special VAT rate.',
    ],
  [
        'start_date' => '2010-07-01',
        'stop_date' => '2016-06-01',
        'territory_codes' => 'GR-83
EL-83',
        'currency_code' => 'EUR',
        'rate' => '0.16',
        'rate_type' => 'standard',
        'description' => 'Lesbos (Greek department) special VAT rate.',
    ],
  [
        'start_date' => '2010-07-01',
        'stop_date' => '2016-06-01',
        'territory_codes' => 'GR-84
EL-84',
        'currency_code' => 'EUR',
        'rate' => '0.16',
        'rate_type' => 'standard',
        'description' => 'Samos (Greek department) special VAT rate.',
    ],
  [
        'start_date' => '2010-07-01',
        'stop_date' => '2016-06-01',
        'territory_codes' => 'GR-85
EL-85',
        'currency_code' => 'EUR',
        'rate' => '0.16',
        'rate_type' => 'standard',
        'description' => 'Chios (Greek department) special VAT rate.',
    ],
  [
        'start_date' => '2011-01-04',
        'stop_date' => '',
        'territory_codes' => 'GS',
        'currency_code' => 'GBP',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'South Georgia and the South Sandwich Islands (British overseas territory) is exempted of VAT.',
    ],
  [
        'start_date' => '2012-03-01',
        'stop_date' => '',
        'territory_codes' => 'HR',
        'currency_code' => 'HRK',
        'rate' => '0.25',
        'rate_type' => 'standard',
        'description' => 'Croatia (member state) standard VAT rate.',
    ],
  [
        'start_date' => '2009-08-01',
        'stop_date' => '2012-03-01',
        'territory_codes' => 'HR',
        'currency_code' => 'HRK',
        'rate' => '0.23',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1998-08-01',
        'stop_date' => '2009-08-01',
        'territory_codes' => 'HR',
        'currency_code' => 'HRK',
        'rate' => '0.22',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2012-01-01',
        'stop_date' => '',
        'territory_codes' => 'HU',
        'currency_code' => 'HUF',
        'rate' => '0.27',
        'rate_type' => 'standard',
        'description' => 'Hungary (member state) standard VAT rate.',
    ],
  [
        'start_date' => '2009-07-01',
        'stop_date' => '2012-01-01',
        'territory_codes' => 'HU',
        'currency_code' => 'HUF',
        'rate' => '0.25',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2006-01-01',
        'stop_date' => '2009-07-01',
        'territory_codes' => 'HU',
        'currency_code' => 'HUF',
        'rate' => '0.2',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1988-01-01',
        'stop_date' => '2006-01-01',
        'territory_codes' => 'HU',
        'currency_code' => 'HUF',
        'rate' => '0.25',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2012-01-01',
        'stop_date' => '',
        'territory_codes' => 'IE',
        'currency_code' => 'EUR',
        'rate' => '0.23',
        'rate_type' => 'standard',
        'description' => 'Republic of Ireland (member state) standard VAT rate.',
    ],
  [
        'start_date' => '2010-01-01',
        'stop_date' => '2012-01-01',
        'territory_codes' => 'IE',
        'currency_code' => 'EUR',
        'rate' => '0.21',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2008-12-01',
        'stop_date' => '2010-01-01',
        'territory_codes' => 'IE',
        'currency_code' => 'EUR',
        'rate' => '0.215',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2002-03-01',
        'stop_date' => '2008-12-01',
        'territory_codes' => 'IE',
        'currency_code' => 'EUR',
        'rate' => '0.21',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2001-01-01',
        'stop_date' => '2002-03-01',
        'territory_codes' => 'IE',
        'currency_code' => 'EUR',
        'rate' => '0.2',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1991-03-01',
        'stop_date' => '2001-01-01',
        'territory_codes' => 'IE',
        'currency_code' => 'EUR',
        'rate' => '0.21',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1990-03-01',
        'stop_date' => '1991-03-01',
        'territory_codes' => 'IE',
        'currency_code' => 'EUR',
        'rate' => '0.23',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1986-03-01',
        'stop_date' => '1990-03-01',
        'territory_codes' => 'IE',
        'currency_code' => 'EUR',
        'rate' => '0.25',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1983-05-01',
        'stop_date' => '1986-03-01',
        'territory_codes' => 'IE',
        'currency_code' => 'EUR',
        'rate' => '0.23',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1983-03-01',
        'stop_date' => '1983-05-01',
        'territory_codes' => 'IE',
        'currency_code' => 'EUR',
        'rate' => '0.35',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1982-05-01',
        'stop_date' => '1983-03-01',
        'territory_codes' => 'IE',
        'currency_code' => 'EUR',
        'rate' => '0.3',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1980-05-01',
        'stop_date' => '1982-05-01',
        'territory_codes' => 'IE',
        'currency_code' => 'EUR',
        'rate' => '0.25',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1976-03-01',
        'stop_date' => '1980-05-01',
        'territory_codes' => 'IE',
        'currency_code' => 'EUR',
        'rate' => '0.2',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1973-09-03',
        'stop_date' => '1976-03-01',
        'territory_codes' => 'IE',
        'currency_code' => 'EUR',
        'rate' => '0.195',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1972-11-01',
        'stop_date' => '1973-09-03',
        'territory_codes' => 'IE',
        'currency_code' => 'EUR',
        'rate' => '0.1637',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2011-01-04',
        'stop_date' => '',
        'territory_codes' => 'IO',
        'currency_code' => 'GBP',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'British Indian Ocean Territory (British overseas territory) is exempted of VAT.',
    ],
  [
        'start_date' => '2013-10-01',
        'stop_date' => '',
        'territory_codes' => 'IT',
        'currency_code' => 'EUR',
        'rate' => '0.22',
        'rate_type' => 'standard',
        'description' => 'Italy (member state) standard VAT rate.',
    ],
  [
        'start_date' => '2011-09-17',
        'stop_date' => '2013-10-01',
        'territory_codes' => 'IT',
        'currency_code' => 'EUR',
        'rate' => '0.21',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1997-10-01',
        'stop_date' => '2011-09-17',
        'territory_codes' => 'IT',
        'currency_code' => 'EUR',
        'rate' => '0.2',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1988-08-01',
        'stop_date' => '1997-10-01',
        'territory_codes' => 'IT',
        'currency_code' => 'EUR',
        'rate' => '0.19',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1982-08-05',
        'stop_date' => '1988-08-01',
        'territory_codes' => 'IT',
        'currency_code' => 'EUR',
        'rate' => '0.18',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1981-01-01',
        'stop_date' => '1982-08-05',
        'territory_codes' => 'IT',
        'currency_code' => 'EUR',
        'rate' => '0.15',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1980-11-01',
        'stop_date' => '1981-01-01',
        'territory_codes' => 'IT',
        'currency_code' => 'EUR',
        'rate' => '0.14',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1980-07-03',
        'stop_date' => '1980-11-01',
        'territory_codes' => 'IT',
        'currency_code' => 'EUR',
        'rate' => '0.15',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1977-02-08',
        'stop_date' => '1980-07-03',
        'territory_codes' => 'IT',
        'currency_code' => 'EUR',
        'rate' => '0.14',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1973-01-01',
        'stop_date' => '1977-02-08',
        'territory_codes' => 'IT',
        'currency_code' => 'EUR',
        'rate' => '0.12',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2013-10-01',
        'stop_date' => '',
        'territory_codes' => 'IT-22060
CH-6911',
        'currency_code' => 'CHF',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Campione (Italian town) is exempted of VAT.',
    ],
  [
        'start_date' => '2013-10-01',
        'stop_date' => '',
        'territory_codes' => 'IT-23030',
        'currency_code' => 'EUR',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Livigno (Italian town) is exempted of VAT.',
    ],
  [
        'start_date' => '2011-01-04',
        'stop_date' => '',
        'territory_codes' => 'JE',
        'currency_code' => 'GBP',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Jersey (British Crown dependency) is exempted of VAT.',
    ],
  [
        'start_date' => '2011-01-04',
        'stop_date' => '',
        'territory_codes' => 'KY',
        'currency_code' => 'KYD',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Cayman Islands (British overseas territory) is exempted of VAT.',
    ],
  [
        'start_date' => '2009-09-01',
        'stop_date' => '',
        'territory_codes' => 'LT',
        'currency_code' => 'EUR',
        'rate' => '0.21',
        'rate_type' => 'standard',
        'description' => 'Lithuania (member state) standard VAT rate.',
    ],
  [
        'start_date' => '2009-01-01',
        'stop_date' => '2009-09-01',
        'territory_codes' => 'LT',
        'currency_code' => 'EUR',
        'rate' => '0.19',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1994-05-01',
        'stop_date' => '2009-01-01',
        'territory_codes' => 'LT',
        'currency_code' => 'EUR',
        'rate' => '0.18',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2015-01-01',
        'stop_date' => '',
        'territory_codes' => 'LU',
        'currency_code' => 'EUR',
        'rate' => '0.17',
        'rate_type' => 'standard',
        'description' => 'Luxembourg (member state) standard VAT rate.',
    ],
  [
        'start_date' => '1992-01-01',
        'stop_date' => '2015-01-01',
        'territory_codes' => 'LU',
        'currency_code' => 'EUR',
        'rate' => '0.15',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1983-07-01',
        'stop_date' => '1992-01-01',
        'territory_codes' => 'LU',
        'currency_code' => 'EUR',
        'rate' => '0.12',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1971-01-01',
        'stop_date' => '1983-07-01',
        'territory_codes' => 'LU',
        'currency_code' => 'EUR',
        'rate' => '0.1',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1970-01-01',
        'stop_date' => '1971-01-01',
        'territory_codes' => 'LU',
        'currency_code' => 'EUR',
        'rate' => '0.8',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2012-07-01',
        'stop_date' => '',
        'territory_codes' => 'LV',
        'currency_code' => 'EUR',
        'rate' => '0.21',
        'rate_type' => 'standard',
        'description' => 'Latvia (member state) standard VAT rate.',
    ],
  [
        'start_date' => '2011-01-01',
        'stop_date' => '2012-07-01',
        'territory_codes' => 'LV',
        'currency_code' => 'EUR',
        'rate' => '0.22',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2009-01-01',
        'stop_date' => '2011-01-01',
        'territory_codes' => 'LV',
        'currency_code' => 'EUR',
        'rate' => '0.21',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1995-05-01',
        'stop_date' => '2009-01-01',
        'territory_codes' => 'LV',
        'currency_code' => 'EUR',
        'rate' => '0.18',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2011-01-04',
        'stop_date' => '',
        'territory_codes' => 'MS',
        'currency_code' => 'XCD',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Montserrat (British overseas territory) is exempted of VAT.',
    ],
  [
        'start_date' => '2004-01-01',
        'stop_date' => '',
        'territory_codes' => 'MT',
        'currency_code' => 'EUR',
        'rate' => '0.18',
        'rate_type' => 'standard',
        'description' => 'Malta (member state) standard VAT rate.',
    ],
  [
        'start_date' => '1995-01-01',
        'stop_date' => '2004-01-01',
        'territory_codes' => 'MT',
        'currency_code' => 'EUR',
        'rate' => '0.15',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2012-10-01',
        'stop_date' => '',
        'territory_codes' => 'NL',
        'currency_code' => 'EUR',
        'rate' => '0.21',
        'rate_type' => 'standard',
        'description' => 'Netherlands (member state) standard VAT rate.',
    ],
  [
        'start_date' => '2001-01-01',
        'stop_date' => '2012-10-01',
        'territory_codes' => 'NL',
        'currency_code' => 'EUR',
        'rate' => '0.19',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1992-10-01',
        'stop_date' => '2001-01-01',
        'territory_codes' => 'NL',
        'currency_code' => 'EUR',
        'rate' => '0.175',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1989-01-01',
        'stop_date' => '1992-10-01',
        'territory_codes' => 'NL',
        'currency_code' => 'EUR',
        'rate' => '0.185',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1986-10-01',
        'stop_date' => '1989-01-01',
        'territory_codes' => 'NL',
        'currency_code' => 'EUR',
        'rate' => '0.2',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1984-01-01',
        'stop_date' => '1986-10-01',
        'territory_codes' => 'NL',
        'currency_code' => 'EUR',
        'rate' => '0.19',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1976-01-01',
        'stop_date' => '1984-01-01',
        'territory_codes' => 'NL',
        'currency_code' => 'EUR',
        'rate' => '0.18',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1973-01-01',
        'stop_date' => '1976-01-01',
        'territory_codes' => 'NL',
        'currency_code' => 'EUR',
        'rate' => '0.16',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1971-01-01',
        'stop_date' => '1973-01-01',
        'territory_codes' => 'NL',
        'currency_code' => 'EUR',
        'rate' => '0.14',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1969-01-01',
        'stop_date' => '1971-01-01',
        'territory_codes' => 'NL',
        'currency_code' => 'EUR',
        'rate' => '0.12',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2012-10-01',
        'stop_date' => '',
        'territory_codes' => 'NL-AW
AW',
        'currency_code' => 'AWG',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Aruba (Dutch country) are exempted of VAT.',
    ],
  [
        'start_date' => '2012-10-01',
        'stop_date' => '',
        'territory_codes' => 'NL-CW
NL-SX
CW
SX',
        'currency_code' => 'ANG',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Curacao and Sint Maarten (Dutch countries) are exempted of VAT.',
    ],
  [
        'start_date' => '2012-10-01',
        'stop_date' => '',
        'territory_codes' => 'NL-BQ1
NL-BQ2
NL-BQ3
BQ
BQ-BO
BQ-SA
BQ-SE',
        'currency_code' => 'USD',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Bonaire, Saba and Sint Eustatius (Dutch special municipalities) are exempted of VAT.',
    ],
  [
        'start_date' => '2011-01-01',
        'stop_date' => '',
        'territory_codes' => 'PL',
        'currency_code' => 'PLN',
        'rate' => '0.23',
        'rate_type' => 'standard',
        'description' => 'Poland (member state) standard VAT rate.',
    ],
  [
        'start_date' => '1993-01-08',
        'stop_date' => '2011-01-01',
        'territory_codes' => 'PL',
        'currency_code' => 'PLN',
        'rate' => '0.22',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2011-01-04',
        'stop_date' => '',
        'territory_codes' => 'PN',
        'currency_code' => 'NZD',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Pitcairn Islands (British overseas territory) is exempted of VAT.',
    ],
  [
        'start_date' => '2011-01-01',
        'stop_date' => '',
        'territory_codes' => 'PT',
        'currency_code' => 'EUR',
        'rate' => '0.23',
        'rate_type' => 'standard',
        'description' => 'Portugal (member state) standard VAT rate.',
    ],
  [
        'start_date' => '2010-07-01',
        'stop_date' => '2011-01-01',
        'territory_codes' => 'PT',
        'currency_code' => 'EUR',
        'rate' => '0.21',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2008-07-01',
        'stop_date' => '2010-07-01',
        'territory_codes' => 'PT',
        'currency_code' => 'EUR',
        'rate' => '0.2',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2005-07-01',
        'stop_date' => '2008-07-01',
        'territory_codes' => 'PT',
        'currency_code' => 'EUR',
        'rate' => '0.21',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2002-06-05',
        'stop_date' => '2005-07-01',
        'territory_codes' => 'PT',
        'currency_code' => 'EUR',
        'rate' => '0.19',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1995-01-01',
        'stop_date' => '2002-06-05',
        'territory_codes' => 'PT',
        'currency_code' => 'EUR',
        'rate' => '0.17',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1992-03-24',
        'stop_date' => '1995-01-01',
        'territory_codes' => 'PT',
        'currency_code' => 'EUR',
        'rate' => '0.16',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1988-02-01',
        'stop_date' => '1992-03-24',
        'territory_codes' => 'PT',
        'currency_code' => 'EUR',
        'rate' => '0.17',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1986-01-01',
        'stop_date' => '1988-02-01',
        'territory_codes' => 'PT',
        'currency_code' => 'EUR',
        'rate' => '0.16',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2011-01-01',
        'stop_date' => '',
        'territory_codes' => 'PT-20',
        'currency_code' => 'EUR',
        'rate' => '0.18',
        'rate_type' => 'standard',
        'description' => 'Azores (Portuguese autonomous region) special VAT rate.',
    ],
  [
        'start_date' => '2011-01-01',
        'stop_date' => '',
        'territory_codes' => 'PT-30',
        'currency_code' => 'EUR',
        'rate' => '0.22',
        'rate_type' => 'standard',
        'description' => 'Madeira (Portuguese autonomous region) special VAT rate.',
    ],
  [
        'start_date' => '2017-01-01',
        'stop_date' => '',
        'territory_codes' => 'RO',
        'currency_code' => 'RON',
        'rate' => '0.19',
        'rate_type' => 'standard',
        'description' => 'Romania (member state) standard VAT rate.',
    ],
  [
        'start_date' => '2016-01-01',
        'stop_date' => '2017-01-01',
        'territory_codes' => 'RO',
        'currency_code' => 'RON',
        'rate' => '0.2',
        'rate_type' => 'standard',
        'description' => 'Romania (member state) standard VAT rate.',
    ],
  [
        'start_date' => '2010-07-01',
        'stop_date' => '2016-01-01',
        'territory_codes' => 'RO',
        'currency_code' => 'RON',
        'rate' => '0.24',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2000-01-01',
        'stop_date' => '2010-07-01',
        'territory_codes' => 'RO',
        'currency_code' => 'RON',
        'rate' => '0.19',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1998-02-01',
        'stop_date' => '2000-01-01',
        'territory_codes' => 'RO',
        'currency_code' => 'RON',
        'rate' => '0.22',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1993-07-01',
        'stop_date' => '1998-02-01',
        'territory_codes' => 'RO',
        'currency_code' => 'RON',
        'rate' => '0.18',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1990-07-01',
        'stop_date' => '',
        'territory_codes' => 'SE',
        'currency_code' => 'SEK',
        'rate' => '0.25',
        'rate_type' => 'standard',
        'description' => 'Sweden (member state) standard VAT rate.',
    ],
  [
        'start_date' => '1983-01-01',
        'stop_date' => '1990-07-01',
        'territory_codes' => 'SE',
        'currency_code' => 'SEK',
        'rate' => '0.2346',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1981-11-16',
        'stop_date' => '1983-01-01',
        'territory_codes' => 'SE',
        'currency_code' => 'SEK',
        'rate' => '0.2151',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1980-09-08',
        'stop_date' => '1981-11-16',
        'territory_codes' => 'SE',
        'currency_code' => 'SEK',
        'rate' => '0.2346',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1977-06-01',
        'stop_date' => '1980-09-08',
        'territory_codes' => 'SE',
        'currency_code' => 'SEK',
        'rate' => '0.2063',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1971-01-01',
        'stop_date' => '1977-06-01',
        'territory_codes' => 'SE',
        'currency_code' => 'SEK',
        'rate' => '0.1765',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1969-01-01',
        'stop_date' => '1971-01-01',
        'territory_codes' => 'SE',
        'currency_code' => 'SEK',
        'rate' => '0.1111',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2011-01-04',
        'stop_date' => '',
        'territory_codes' => 'AC
SH
SH-AC
SH-HL',
        'currency_code' => 'SHP',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Ascension and Saint Helena (British overseas territory) is exempted of VAT.',
    ],
  [
        'start_date' => '2011-01-04',
        'stop_date' => '',
        'territory_codes' => 'TA
SH-TA',
        'currency_code' => 'GBP',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Tristan da Cunha (British oversea territory) is exempted of VAT.',
    ],
  [
        'start_date' => '2013-07-01',
        'stop_date' => '',
        'territory_codes' => 'SI',
        'currency_code' => 'EUR',
        'rate' => '0.22',
        'rate_type' => 'standard',
        'description' => 'Slovenia (member state) standard VAT rate.',
    ],
  [
        'start_date' => '2002-01-01',
        'stop_date' => '2013-07-01',
        'territory_codes' => 'SI',
        'currency_code' => 'EUR',
        'rate' => '0.2',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1999-07-01',
        'stop_date' => '2002-01-01',
        'territory_codes' => 'SI',
        'currency_code' => 'EUR',
        'rate' => '0.19',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2011-01-01',
        'stop_date' => '',
        'territory_codes' => 'SK',
        'currency_code' => 'EUR',
        'rate' => '0.2',
        'rate_type' => 'standard',
        'description' => 'Slovakia (member state) standard VAT rate.',
    ],
  [
        'start_date' => '2004-01-01',
        'stop_date' => '2011-01-01',
        'territory_codes' => 'SK',
        'currency_code' => 'EUR',
        'rate' => '0.19',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2003-01-01',
        'stop_date' => '2004-01-01',
        'territory_codes' => 'SK',
        'currency_code' => 'EUR',
        'rate' => '0.2',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1996-01-01',
        'stop_date' => '2003-01-01',
        'territory_codes' => 'SK',
        'currency_code' => 'EUR',
        'rate' => '0.23',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1993-08-01',
        'stop_date' => '1996-01-01',
        'territory_codes' => 'SK',
        'currency_code' => 'EUR',
        'rate' => '0.25',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1993-01-01',
        'stop_date' => '1993-08-01',
        'territory_codes' => 'SK',
        'currency_code' => 'EUR',
        'rate' => '0.23',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2011-01-04',
        'stop_date' => '',
        'territory_codes' => 'TC',
        'currency_code' => 'USD',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Turks and Caicos Islands (British overseas territory) is exempted of VAT.',
    ],
  [
        'start_date' => '2011-01-04',
        'stop_date' => '',
        'territory_codes' => 'GB
UK
IM',
        'currency_code' => 'GBP',
        'rate' => '0.2',
        'rate_type' => 'standard',
        'description' => 'United Kingdom (member state) standard VAT rate.
Isle of Man (British self-governing dependency) is member of the EU VAT area and subjected to UK\'s standard VAT rate.',
    ],
  [
        'start_date' => '2010-01-01',
        'stop_date' => '2011-01-04',
        'territory_codes' => 'GB
UK
IM',
        'currency_code' => 'GBP',
        'rate' => '0.175',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2008-12-01',
        'stop_date' => '2010-01-01',
        'territory_codes' => 'GB
UK
IM',
        'currency_code' => 'GBP',
        'rate' => '0.15',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1991-04-01',
        'stop_date' => '2008-12-01',
        'territory_codes' => 'GB
UK
IM',
        'currency_code' => 'GBP',
        'rate' => '0.175',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1979-06-18',
        'stop_date' => '1991-04-01',
        'territory_codes' => 'GB
UK
IM',
        'currency_code' => 'GBP',
        'rate' => '0.15',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1974-07-29',
        'stop_date' => '1979-06-18',
        'territory_codes' => 'GB
UK
IM',
        'currency_code' => 'GBP',
        'rate' => '0.08',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '1973-04-01',
        'stop_date' => '1974-07-29',
        'territory_codes' => 'GB
UK
IM',
        'currency_code' => 'GBP',
        'rate' => '0.1',
        'rate_type' => 'standard',
        'description' => '',
    ],
  [
        'start_date' => '2011-01-04',
        'stop_date' => '',
        'territory_codes' => 'VG',
        'currency_code' => 'USD',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'British Virgin Islands (British overseas territory) is exempted of VAT.',
    ],
  [
        'start_date' => '2014-01-01',
        'stop_date' => '',
        'territory_codes' => 'CP',
        'currency_code' => 'EUR',
        'rate' => '0',
        'rate_type' => 'standard',
        'description' => 'Clipperton Island (French overseas possession) is exempted of VAT.',
    ],
];
